version: '3.4'
services:
  db:
    container_name: db
    image: mongo
    volumes:
      - /mongo/data/pollofeed:/data/db
    env_file:
      - .env.mongo
    ports:
      - 27017:27017
    restart: always
    networks:
      - nginxproxy
    healthcheck:
      test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/${MONGO_DB_NAME} --quiet` ] && echo 0 || echo 1"
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3
  pollofeed:
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    container_name: pollofeed
    build: .
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - nginxproxy
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

networks:
  nginxproxy:
    external:
      name: nginxproxy


